multipart:
 maxFileSize: 100Mb
 maxRequestSize: 1000Mb
 
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates
    suffix: .html
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/cmdbuild_ziguan
    username: postgres
    password: postgres
server:
  port: 8081